"""
Canonical list of doc-guard test modules.

Doc-guard tests verify documentation artifacts (Markdown files, JSON evidence
bundles, scope-guard invariants) rather than application behaviour.  They are
correct and should still pass, but they must not be confused with functional
tests when assessing code coverage or regression safety.

Used by:
  - backend/tests/conftest.py     (pytest marker injection)
  - scripts/run-functional-tests.sh  (standalone unittest runner)

When a new GL-NNN issue adds only documentation artifacts, add its test
module name here so it is automatically excluded from the functional run.
"""

DOC_GUARD_MODULES: frozenset[str] = frozenset(
    [
        "test_gl054_demo_scenario_fixture",
        "test_gl055_integration_contract_readiness",
        "test_gl057_integrator_quickstart_examples",
        "test_gl058_minimal_api_usage_walkthrough",
        "test_gl059_pilot_ready_handoff",
        "test_gl060_pilot_ready_release_decision",
        "test_gl061_demo_runner_api_smoke",
        "test_gl062_pilot_partner_preparation_pack",
        "test_gl063_production_hardening_roadmap",
        "test_gl064_api_openapi_contract_hardening_review",
        "test_gl065_product_architecture_extension_boundaries",
        "test_gl066_runtime_configuration_environment_model",
        "test_gl067_production_auth_operator_access_design",
        "test_gl068_secret_management_baseline_design",
        "test_gl069_deployment_package_runtime_modes_design",
        "test_gl070_persistence_backend_postgresql_readiness",
        "test_gl071_observability_structured_logging_baseline",
        "test_gl072_backup_restore_data_lifecycle_design",
        "test_gl073_operational_runbook_incident_response",
        "test_gl074_product_foundation_readiness_cut",
        "test_gl075_product_foundation_claude_review_gate",
        "test_gl075b_product_foundation_claude_independent_review",
        "test_gl078_structured_logging_correlation_helper",
        "test_gl085_security_data_integrity_followup_review",
        "test_gl094a_phase1_security_review_artifact",
        "test_gl094b_audit_log_immutability_review_artifact",
        "test_gl094c_production_architecture_operations_review_artifact",
        "test_gl101_full_product_readiness_gap_review",
        "test_gl115_security_data_integrity_validation_review_gate",
        "test_gl121_full_suite_runner",
        "test_gl127_backup_restore_minimum_drill",
        "test_gl128_pilot_readiness_release_cut",
        "test_gl129_monitoring_alerting_baseline",
        "test_gl130_incident_response_runbook_execution_gate",
        "test_gl131_pilot_environment_setup_checklist",
        "test_gl132_tenant_workspace_boundary_decision",
        "test_gl133_external_security_review_preparation",
        "test_gl134_pilot_partner_dry_run",
        "test_gl135_security_remediation_intake",
        "test_gl136_key_hygiene",
        "test_gl137_dependency_manifest",
        "test_gl138_check_admin_token_cleanup",
        "test_gl140_threading_http_server_enablement",
        "test_gl143_server_route_decomposition_plan",
        "test_gl144_tenant_workspace_data_model_design",
        "test_gl145_developer_adoption_strategy_intake",
        "test_gl146_ten_minute_quickstart",
        "test_gl147_minimal_python_sdk",
        "test_gl148_langgraph_langchain_integration_example",
        "test_gl149_public_github_readiness_pack",
        "test_gl150_first_developer_feedback_log",
        "test_gl151_public_readme_repo_metadata_polish",
        "test_gl152_public_checklist_blocker_fixes",
        "test_gl153_license_contributing_security_decision",
        "test_gl154_agent_entry_points_manifest",
        "test_gl156_github_issue_feedback_templates",
        "test_gl157_public_secret_sensitive_scan_gate",
        "test_gl158_git_history_exposure_review_public_snapshot_decision",
        "test_gl159_github_private_mirror_dry_run",
        "test_gl160_public_github_go_no_go_decision",
        "test_gl161_clean_public_snapshot_build",
        "test_gl162_github_public_repository_publish_gate",
        "test_gl162b_public_snapshot_scanner_clean_export",
        "test_gl162c_public_snapshot_ci_compatibility",
        "test_gl162f_dashboard_xss_hardening",
        "test_gl163_post_public_agent_intake_triage",
        "test_gl164a_public_repo_discovery_metadata",
        "test_gl165_public_changelog_version_anchors",
        "test_gl167_public_visibility_go_no_go_checklist",
        "test_gl169_quickstart_public_repo_polish",
        "test_gl170_status_block_deduplication",
        "test_gl171_public_release_github_snapshot_readiness_review",
        "test_gl172_public_snapshot_publish_gate",
        "test_gl173_public_snapshot_post_publish_smoke_review",
        "test_gl174_public_snapshot_human_review_gate",
        "test_gl175_public_snapshot_visibility_decision_gate",
        "test_gl176_public_github_visibility_change_report",
        "test_gl177_public_repo_smoke_verification",
        "test_gl178_readme_security_post_public_state",
        "test_gl180_public_docs_smoke_verification",
        "test_gl181_public_snapshot_exclusion_cleanup",
        "test_gl182_external_developer_feedback_intake",
        "test_gl183_external_feedback_triage_public_issue_hygiene",
        "test_gl184_first_external_reviewer_invite_pack",
        "test_gl185_first_reviewer_feedback_window",
        "test_gl186_ai_reviewer_feedback_triage",
        "test_gl187_public_docs_post_public_stale_claim_cleanup",
        "test_gl187p_public_snapshot_correction_push",
        "test_gl188_first_output_verify_helper",
        "test_gl188p_public_snapshot_correction_push",
        "test_gl189_grant_lifecycle_evidence_bundle",
        "test_gl191_public_developer_experience_polish_pack",
        "test_gl192_public_feedback_infrastructure_pack",
        "test_gl193_public_agent_api_walkthrough_refresh",
        "test_gl194_public_preview_review_feedback_triage_pack",
        "test_gl195_public_safety_scanner_claim_consistency_gate",
        "test_gl196_public_smoke_matrix_pack",
        "test_gl197_api_sdk_agent_value_decision_pack",
        "test_gl198_controlled_preview_boundary_pack",
        "test_gl199_production_readiness_gap_report_v2",
        "test_gl200a_tenant_workspace_isolation_design_pack",
        "test_gl203_api_contract_sdk_packaging_decision",
        "test_gl203b_openapi_api_contract_cleanup",
        "test_gl203c_sdk_prototype_packaging_boundary",
        "test_gl204_production_ops_go_no_go_v3",
        "test_gl205_live_postgres_backup_observability_baseline",
        "test_gl206b_live_postgres_validation_execution",
        "test_gl207_claim_safety_controlled_preview_boundary",
        "test_gl209_data_governance_audit_operations",
        "test_gl210_website_track",
        "test_gl211_sdk_pilot_production_gate",
        "test_gl212_public_external_review_readiness_gate_pack",
        "test_gl213_production_readiness_gap_report_v4",
        "test_gl214_production_iam_operator_control_completion",
        "test_gl216_production_operations_hardening_pack",
        "test_gl217_production_go_no_go_v5",
        "test_gl218_public_external_review_export_safety_pack",
        "test_gl220_production_runtime_infrastructure_hardening_pack",
        "test_gl221_workspace_enforcement_final_go_no_go_v6",
        "test_gl223_workspace_identity_membership_ownership_implementation_plan",
        "test_gl234_public_repo_cleanup",
    ]
)
