"""Tests for GL-069 Deployment Package and Runtime Modes Design.

Lightweight validation test proving the deployment package and runtime modes design is:
- present as a human-readable document
- present as machine-readable JSON files
- coherent with referenced Pilot-Ready and Production-Hardening artifacts
- explicitly defining runtime mode mapping, package components, safe defaults,
  production-required deployment behavior, and deployment boundaries
- free of obvious secrets
- not introducing forbidden implementation files
"""

import json
import pathlib
import unittest


class TestGL069DeploymentPackageRuntimeModesDesign(unittest.TestCase):
    """GL-069: Validate deployment package and runtime modes design."""

    REPO_ROOT = pathlib.Path(__file__).with_suffix("").parent.parent.parent
    DOCS_DIR = REPO_ROOT / "docs"
    EXAMPLE_DIR_GL069 = DOCS_DIR / "examples" / "gl069"
    BACKEND_SRC_DIR = REPO_ROOT / "backend" / "src"

    REQUIRED_RUNTIME_MODES = [
        "local-dev",
        "test",
        "demo",
        "integration",
        "staging",
        "production",
    ]

    REQUIRED_PACKAGE_COMPONENTS = [
        "application-package",
        "configuration-schema",
        "runtime-mode-declaration",
        "database-persistence-configuration",
        "secret-source-configuration",
        "auth-operator-access-configuration",
        "evidence-storage-configuration",
        "policy-rule-pack-configuration",
        "observability-logging-configuration",
        "backup-restore-configuration",
        "health-readiness-checks",
        "api-openapi-contract-artifact",
        "demo-sample-data-bundle",
        "integration-example-bundle",
        "operator-runbook",
        "upgrade-migration-notes",
        "extension-adaptor-configuration",
        "production-hardening-checklist",
    ]

    REQUIRED_PRODUCTION_DEPLOYMENT_CONFIGURATIONS = [
        "runtime mode",
        "deployment environment context",
        "database/persistence backend",
        "secret source",
        "auth/operator access",
        "evidence storage",
        "observability/logging",
        "backup/restore plan",
        "network binding/exposure",
        "health/readiness checks",
        "production hardening checklist",
        "fail-closed",
    ]

    SECRET_PATTERNS = [
        "password",
        "secret",
        "token",
        "api_key",
        "apikey",
        "private_key",
        "privatekey",
        "bearer",
        "authorization",
    ]

    FORBIDDEN_PATH_PATTERNS = [
        BACKEND_SRC_DIR / "config_loader.py",
        BACKEND_SRC_DIR / "runtime_config.py",
        BACKEND_SRC_DIR / "environment.py",
        BACKEND_SRC_DIR / "settings.py",
        BACKEND_SRC_DIR / "secrets.py",
        BACKEND_SRC_DIR / "vault.py",
        BACKEND_SRC_DIR / "auth_provider.py",
        BACKEND_SRC_DIR / "oauth.py",
        BACKEND_SRC_DIR / "jwt.py",
        BACKEND_SRC_DIR / "sso.py",
        BACKEND_SRC_DIR / "mtls.py",
        BACKEND_SRC_DIR / "observability.py",
        BACKEND_SRC_DIR / "metrics.py",
        BACKEND_SRC_DIR / "prometheus.py",
        BACKEND_SRC_DIR / "grafana.py",
        BACKEND_SRC_DIR / "backup.py",
        BACKEND_SRC_DIR / "restore.py",
        BACKEND_SRC_DIR / "s3_storage.py",
        BACKEND_SRC_DIR / "hsm.py",
        BACKEND_SRC_DIR / "blockchain.py",
        BACKEND_SRC_DIR / "wallet.py",
        BACKEND_SRC_DIR / "payment.py",
        BACKEND_SRC_DIR / "tenant.py",
        BACKEND_SRC_DIR / "saas.py",
        BACKEND_SRC_DIR / "dashboard.py",
        BACKEND_SRC_DIR / "ui.py",
        BACKEND_SRC_DIR / "frontend.py",
        BACKEND_SRC_DIR / "sdk.py",
        BACKEND_SRC_DIR / "client.py",
        BACKEND_SRC_DIR / "deploy.py",
        BACKEND_SRC_DIR / "docker.py",
        BACKEND_SRC_DIR / "kubernetes.py",
        BACKEND_SRC_DIR / "helm.py",
        BACKEND_SRC_DIR / "terraform.py",
        BACKEND_SRC_DIR / "ci.py",
        BACKEND_SRC_DIR / "gitlab.py",
        BACKEND_SRC_DIR / "github.py",
    ]

    @classmethod
    def setUpClass(cls):
        cls.doc_path = cls.DOCS_DIR / "deployment_package_runtime_modes_design.md"
        cls.matrix_path = cls.EXAMPLE_DIR_GL069 / "deployment_runtime_mode_matrix.json"
        cls.catalog_path = cls.EXAMPLE_DIR_GL069 / "deployment_package_catalog.json"

        cls.matrix_json = None
        cls.matrix_text = None
        if cls.matrix_path.exists():
            cls.matrix_text = cls.matrix_path.read_text(encoding="utf-8")
            cls.matrix_json = json.loads(cls.matrix_text)

        cls.catalog_json = None
        cls.catalog_text = None
        if cls.catalog_path.exists():
            cls.catalog_text = cls.catalog_path.read_text(encoding="utf-8")
            cls.catalog_json = json.loads(cls.catalog_text)

    # ── 1. Deployment package doc exists ──────────────────────────────
    def test_deployment_package_doc_exists(self):
        self.assertTrue(
            self.doc_path.exists(),
            "docs/deployment_package_runtime_modes_design.md must exist",
        )

    # ── 2. Deployment runtime mode matrix JSON exists and parses ──────
    def test_matrix_exists_and_parses(self):
        self.assertTrue(
            self.matrix_path.exists(),
            "docs/examples/gl069/deployment_runtime_mode_matrix.json must exist",
        )
        self.assertIsNotNone(self.matrix_json, "Matrix must parse as valid JSON")
        self.assertIsInstance(self.matrix_json, dict)

    # ── 3. Deployment package catalog JSON exists and parses ──────────
    def test_catalog_exists_and_parses(self):
        self.assertTrue(
            self.catalog_path.exists(),
            "docs/examples/gl069/deployment_package_catalog.json must exist",
        )
        self.assertIsNotNone(self.catalog_json, "Catalog must parse as valid JSON")
        self.assertIsInstance(self.catalog_json, dict)

    # ── 4. Required product-foundation docs exist ─────────────────────
    def test_required_product_foundation_docs_exist(self):
        required = [
            "integration_guide.md",
            "integrator_quickstart.md",
            "minimal_api_usage_walkthrough.md",
            "demo_scenario.md",
            "pilot_ready_handoff_plan.md",
            "pilot_ready_release_decision.md",
            "demo_runner_api_smoke.md",
            "pilot_partner_preparation_pack.md",
            "production_hardening_roadmap.md",
            "production_readiness_cut.md",
            "product_architecture_extension_boundaries.md",
            "api_openapi_contract_hardening_review.md",
        ]
        missing = []
        for name in required:
            path = self.DOCS_DIR / name
            if not path.exists():
                missing.append(name)
        self.assertEqual(missing, [], f"Missing required docs: {missing}")

    # ── 5. GL-068 secret management baseline doc exists ──────────────
    def test_gl068_secret_management_doc_exists(self):
        path = self.DOCS_DIR / "secret_management_baseline_design.md"
        self.assertTrue(path.exists(), "GL-068 secret management baseline doc must exist")

    # ── 6. GL-067 auth/operator access doc exists ────────────────────
    def test_gl067_auth_operator_access_doc_exists(self):
        path = self.DOCS_DIR / "production_auth_operator_access_design.md"
        self.assertTrue(path.exists(), "GL-067 auth/operator access doc must exist")

    # ── 7. GL-066 runtime configuration doc exists ───────────────────
    def test_gl066_runtime_configuration_doc_exists(self):
        path = self.DOCS_DIR / "runtime_configuration_environment_model.md"
        self.assertTrue(path.exists(), "GL-066 runtime configuration doc must exist")

    # ── 8. Deployment runtime matrix includes required runtime modes ──
    def test_matrix_includes_required_runtime_modes(self):
        modes = self.matrix_json.get("runtimeModes", [])
        mode_names = {m.get("mode") for m in modes}
        for expected in self.REQUIRED_RUNTIME_MODES:
            with self.subTest(mode=expected):
                self.assertIn(
                    expected,
                    mode_names,
                    f"Matrix must include runtime mode '{expected}'",
                )

    # ── 9. Deployment package catalog includes required package components ─
    def test_catalog_includes_required_package_components(self):
        components = self.catalog_json.get("packageComponents", [])
        component_ids = {c.get("id") for c in components}
        for expected in self.REQUIRED_PACKAGE_COMPONENTS:
            with self.subTest(component=expected):
                self.assertIn(
                    expected,
                    component_ids,
                    f"Catalog must include package component '{expected}'",
                )

    # ── 10. Production deployment required configuration includes key areas ─
    def test_production_required_configuration_includes_key_areas(self):
        # Check matrix
        matrix_required = self.matrix_json.get("productionRequiredDeploymentConfiguration", [])
        matrix_text = " ".join(matrix_required).lower()
        for expected in self.REQUIRED_PRODUCTION_DEPLOYMENT_CONFIGURATIONS:
            with self.subTest(area=expected):
                self.assertIn(
                    expected.lower(),
                    matrix_text,
                    f"Matrix productionRequiredDeploymentConfiguration must include '{expected}'",
                )
        # Check catalog
        catalog_required = self.catalog_json.get("productionRequiredConfiguration", [])
        catalog_text = " ".join(catalog_required).lower()
        for expected in self.REQUIRED_PRODUCTION_DEPLOYMENT_CONFIGURATIONS:
            with self.subTest(area=expected):
                self.assertIn(
                    expected.lower(),
                    catalog_text,
                    f"Catalog productionRequiredConfiguration must include '{expected}'",
                )

    # ── 11. Document states local/demo/test convenience must not become production behavior ─
    def test_doc_states_local_demo_test_not_production(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("local, demo, and test convenience must not accidentally become production deployment behavior", content)
        self.assertIn("not valid production deployment behavior", content)

    # ── 12. Document states production deployment readiness is not yet claimed ─
    def test_doc_states_production_deployment_readiness_not_claimed(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn(
            "claim production deployment readiness",
            content,
        )
        self.assertIn(
            "runtime mode, configuration, secrets, auth, persistence, observability, backup/restore, health checks, and deployment hardening",
            content,
        )

    # ── 13. JSON files do not contain obvious secrets, fake tokens, fake keys, or fake credentials ─
    def _sanitize_known_safe_terms(self, text):
        """Remove legitimate planning terms that contain secret-like substrings."""
        safe_terms = [
            "secret",
            "secrets",
            "secret management baseline design",
            "secret management baseline",
            "secret management",
            "secret-handling-policy-catalog",
            "secret-handling",
            "secret_handling_policy_catalog",
            "secret inventory model",
            "secret_inventory_model",
            "secret inventory",
            "secret source abstraction",
            "secret source boundary",
            "secret source",
            "secret source names",
            "secret source manager",
            "secret source expectation",
            "secret source validation",
            "secret configuration schema",
            "secret configuration",
            "secret-bearing configuration",
            "secret-bearing fields",
            "secret-bearing config",
            "secret redaction helper",
            "secret redaction",
            "secret values",
            "secret value",
            "secret categories",
            "secret category",
            "secret categories define",
            "secret inventory model",
            "secret handling policy catalog",
            "secret handling boundary",
            "secret handling boundaries",
            "secret handling expectations",
            "secret handling principle",
            "secret handling clarity",
            "secret handling baseline",
            "secret handling",
            "secret placeholder",
            "secret placeholders",
            "secret expectation",
            "secret expectations",
            "secret resolved",
            "secret resolution",
            "secret category identifier",
            "secret manager",
            "secret managers",
            "secret store",
            "secret storage",
            "secret leakage",
            "secret leak",
            "secret loader",
            "secret loader implementation",
            "secret load",
            "secret material",
            "secret key",
            "secret identifier",
            "secret-bearing",
            "secret-boundary",
            "secret-boundary calls",
            "secret-bearing output",
            "secret-bearing field",
            "secrets must not",
            "secrets outside",
            "secrets are needed",
            "secrets do not",
            "secrets should",
            "secrets must",
            "secrets may",
            "secrets were",
            "secrets in",
            "secrets from",
            "secrets through",
            "secrets outside",
            "secrets in logs",
            "secrets in exports",
            "secrets in examples",
            "secrets in fixtures",
            "secrets in evidence",
            "secrets in records",
            "secrets in git",
            "secrets in source",
            "secrets in test",
            "secrets in diagnostics",
            "secrets in backup",
            "secrets in config",
            "secrets in the",
            "required secrets",
            "managed secrets",
            "managed secret",
            "managed secret boundary",
            "managed secret strategy",
            "managed secret source",
            "managed with rotation",
            "placeholder secrets",
            "placeholder secret",
            "demo secrets",
            "demo secret",
            "synthetic secrets",
            "synthetic secret",
            "real secrets",
            "real secret",
            "external secret manager",
            "external secret managers",
            "no external secret manager",
            "local secret",
            "production secrets",
            "production secret",
            "auth provider credentials",
            "auth provider secret",
            "auth provider secret configuration",
            "auth provider secrets",
            "session token signing secrets",
            "session signing secrets",
            "session signing",
            "session tokens",
            "session token",
            "signing key material",
            "signing key management",
            "signing key",
            "signing keys",
            "signing and key management",
            "signing secret",
            "signing secrets",
            "signing operation",
            "signing algorithm",
            "demo signing key",
            "key identifier",
            "key identifiers",
            "key management",
            "key management abstraction",
            "key management source",
            "key rotation",
            "key source",
            "key provider",
            "key material",
            "key store",
            "key pair",
            "keypair",
            "synthetic keypairs",
            "synthetic keypair",
            "demo keypairs",
            "demo keypair",
            "mock key reference",
            "mock encryption key",
            "mock signing secret",
            "mock provider configuration",
            "mock provider",
            "mock secret",
            "mock secret sources",
            "mock secret source",
            "mock service identity",
            "mock shared secret",
            "mock client identifier",
            "mock sink reference",
            "mock provider references",
            "database credential source",
            "database credential configuration",
            "database credentials",
            "database credential",
            "evidence storage credentials",
            "evidence storage credential",
            "evidence storage credential configuration",
            "evidence storage credential source",
            "backup storage credentials",
            "backup storage credential",
            "observability sink credentials",
            "observability sink credential",
            "observability sink secret",
            "observability sink secret configuration",
            "external integration credentials",
            "external integration credential",
            "external integration secret",
            "external integration secret adapter",
            "api client credentials",
            "api client credential",
            "service-to-service credentials",
            "service-to-service credential",
            "service identity provider",
            "service credentials",
            "service credential",
            "webhook secrets",
            "webhook secret",
            "encryption keys",
            "encryption key",
            "token references",
            "token reference",
            "token signing",
            "token source",
            "tokens",
            "token",
            "demo tokens",
            "demo token",
            "demo admin tokens",
            "demo admin token",
            "test tokens",
            "synthetic tokens",
            "placeholder tokens",
            "local admin token",
            "admin tokens",
            "admin token",
            "operator tokens",
            "operator token",
            "session token",
            "state token",
            "auth token",
            "auth artifacts",
            "bearer",
            "authorization",
            "api_key",
            "apikey",
            "private_key",
            "privatekey",
            "password",
            "passwords",
            "password login",
            "default passwords",
            "client secrets",
            "client secret",
            "shared secrets",
            "shared secret",
            "placeholder identifiers",
            "placeholder identifier",
            "placeholder labels",
            "placeholder label",
            "demo fixture identifiers",
            "demo fixture identifier",
            "synthetic fixture identifiers",
            "synthetic fixture",
            "synthetic fixtures",
            "synthetic data",
            "synthetic identities",
            "synthetic identity",
            "synthetic labels",
            "synthetic label",
            "synthetic operator",
            "synthetic service",
            "deterministic placeholder identifiers",
            "deterministic test identity",
            "deterministic test",
            "deterministic test seeds",
            "demo operator identity",
            "demo operator",
            "fixture-based service identity",
            "fixture-based",
            "fixture ids",
            "fixture id",
            "fixture identifiers",
            "fixture identifier",
            "readonly demo access",
            "demo readonly",
            "local demo shortcut",
            "local demo shortcut guard",
            "local test demo shortcut",
            "local test demo",
            "local test",
            "local dev",
            "local file path",
            "local file paths",
            "local-only demo",
            "local-only",
            "local sqlite",
            "local admin",
            "local binding",
            "local config",
            "local development",
            "dry-run-only",
            "dry run",
            "smoke manifests",
            "secret identifier",
            "secret identifiers",
            "secret resolution",
            "secret values",
            "secret value",
            "secret manager integration",
            "secret manager",
            "secret handling policy",
            "secret handling",
            "secret handling expectations",
            "secret handling baseline",
            "secret handling boundary",
            "secret handling boundaries",
            "secret handling policy catalog",
            "secret inventory",
            "secret inventory model",
            "secret category",
            "secret categories",
            "secret source",
            "secret sources",
            "secret store",
            "secret storage",
            "secret redaction",
            "secret redaction helper",
            "secret leakage",
            "secret leak",
            "secret leak into",
            "secret leak prevention",
            "leakage prevention",
            "leakage prevention tests",
            "leakage prevention expectations",
            "fail-closed startup",
            "fail-closed startup checks",
            "fail closed startup",
            "fail closed",
            "fail-closed secret",
            "fail-closed behavior",
            "fail closed behavior",
            "startup check",
            "startup checks",
            "startup logs",
            "startup output",
            "startup banner",
            "startup must",
            "startup allowed",
            "startup if",
            "startup behavior",
            "runtime secret",
            "runtime secret source",
            "runtime secret validation",
            "runtime secret expectations",
            "runtime secret expectation",
            "runtime mode secret",
            "runtime mode",
            "runtime configuration",
            "runtime config",
            "runtime behavior",
            "runtime secret",
            "runtime modes",
            "missing secret",
            "missing secrets",
            "missing required secret",
            "missing required secrets",
            "required secret",
            "required secrets",
            "required secret source",
            "required secret sources",
            "required secret configuration",
            "explicit secret",
            "explicit secrets",
            "explicit secret source",
            "explicit secret sources",
            "explicit secret boundary",
            "explicit secret management",
            "explicit secret configuration",
            "explicit signing",
            "explicit signing key",
            "explicit signing and key management",
            "explicit database credential",
            "explicit database credentials",
            "explicit auth provider",
            "explicit auth provider credential",
            "explicit auth provider credentials",
            "explicit evidence storage",
            "explicit evidence storage credential",
            "explicit observability",
            "explicit observability sink",
            "explicit managed",
            "explicit managed secret",
            "explicit managed key",
            "explicit managed encryption",
            "explicit scoped",
            "explicit scoped backup",
            "explicit scoped credential",
            "explicit scoped credentials",
            "explicit scoped client",
            "explicit external integration",
            "explicit service identity",
            "explicit operator",
            "explicit bootstrap",
            "explicit provider",
            "explicit configuration",
            "explicit config",
            "explicit non-production",
            "explicit validated",
            "explicit validated source",
            "explicit validated secret",
            "explicit production-grade",
            "production secret",
            "production secrets",
            "production secret management",
            "production secret readiness",
            "production secret source",
            "production secret sources",
            "production secret expectation",
            "production secret expectations",
            "production secret boundary",
            "production secret configuration",
            "production secret behavior",
            "production required secret",
            "production required secrets",
            "production claim",
            "production claim boundary",
            "production claim requires",
            "production claim is",
            "production readiness",
            "production hardening",
            "production-hardening",
            "production environment",
            "production mode",
            "production modes",
            "production config",
            "production configuration",
            "production behavior",
            "production use",
            "production deployment",
            "production observability",
            "production database",
            "production auth",
            "production operator",
            "production storage",
            "production network",
            "production failure",
            "production output",
            "production log",
            "production logs",
            "production required",
            "production explicit",
            "production validated",
            "production validated source",
            "production-like",
            "production-like secret",
            "production-like validation",
            "production-like durability",
            "production-like behavior",
            "non-production",
            "non-production constraint",
            "non-production modes",
            "non-production mode",
            "non-production walkthrough",
            "non-production labeling",
            "not production",
            "not production-ready",
            "not described as production-ready",
            "not valid production",
            "not valid production secrets",
            "not valid production behavior",
            "not yet claimed",
            "not be described as production-ready",
            "secret management readiness",
            "secret management readiness is not yet claimed",
            "claim production secret management readiness",
            "claim production readiness",
            "auth provider",
            "auth provider adapter",
            "auth provider credentials",
            "auth provider secret",
            "auth provider configuration",
            "auth provider role mapping",
            "auth provider type",
            "auth provider endpoint",
            "auth provider integration",
            "auth provider claim",
            "auth provider with validated",
            "auth provider with",
            "authentication provider",
            "auth expectation",
            "auth expectations",
            "auth shortcuts",
            "auth shortcut",
            "auth path",
            "auth success",
            "auth failure",
            "auth audit event",
            "auth configuration",
            "auth config",
            "auth gate",
            "auth provider secrets",
            "auth provider secret configuration",
            "external identity provider",
            "service identity provider",
            "identity provider",
            "mock auth provider",
            "no external identity provider",
            "operator identity",
            "operator identities",
            "operator bootstrap",
            "operator role",
            "operator roles",
            "operator access",
            "operator/admin",
            "operator actions",
            "operator-sensitive",
            "readonly integration",
            "readonly integrator",
            "readonly demo",
            "readonly access",
            "external workflow agent",
            "service operator",
            "service-to-service",
            "service identity",
            "service actions",
            "service credentials",
            "workflow execution",
            "workflow steps",
            "workflow agents",
            "workflow orchestrator",
            "grant approval",
            "grant request",
            "grant admin",
            "grant creation",
            "grant lifecycle",
            "evidence write",
            "evidence verification",
            "evidence storage",
            "evidence bundle",
            "evidence bundles",
            "evidence persistence",
            "evidence metadata",
            "evidence completeness",
            "evidence operator",
            "policy admin",
            "policy rule",
            "policy changes",
            "policy requirements",
            "policy evaluation",
            "permission profile",
            "permission profiles",
            "permission evaluation",
            "permission changes",
            "audit event",
            "audit events",
            "audit records",
            "audit record",
            "audit trail",
            "audit export",
            "audit expectation",
            "audit expectations",
            "audit stream",
            "audit and provenance",
            "auditor export",
            "auditor exports",
            "auditor review",
            "compliance readiness",
            "compliance gap",
            "compliance review",
            "compliance readiness summaries",
            "compliance readiness summary",
            "compliance/legal",
            "decision provenance",
            "provenance records",
            "provenance summaries",
            "provenance summary",
            "provenance event",
            "provenance events",
            "provenance record",
            "institutional audit",
            "institutional records",
            "institutional data",
            "data sensitivity",
            "data classification",
            "data integrity",
            "data flow",
            "data privacy",
            "sensitive data",
            "sensitive fields",
            "sensitive value",
            "sensitive values",
            "configuration boundary",
            "config boundary",
            "config dumps",
            "config files",
            "configuration schema",
            "configuration categories",
            "configuration catalog",
            "configuration loader",
            "configuration-driven",
            "environment boundary",
            "environment model",
            "environment variables",
            "validated environment",
            "runtime configuration",
            "runtime mode",
            "runtime modes",
            "runtime behavior",
            "runtime secret",
            "runtime environment",
            "feature flags",
            "extension toggles",
            "extension boundaries",
            "extension boundary",
            "extension adapter",
            "extension surface",
            "extension surfaces",
            "replaceable adapter",
            "replaceable adapters",
            "product core",
            "product core records",
            "product core state",
            "product core logic",
            "product core contracts",
            "product core domain",
            "product core owned",
            "product core must",
            "product core should",
            "product core does",
            "product core secret",
            "product core read",
            "product core records",
            "product core owned",
            "product core boundary",
            "public contracts",
            "stable contracts",
            "stable public contracts",
            "stable product core",
            "stable operator",
            "stable operator role",
            "stable operator roles",
            "stable identity",
            "stable identities",
            "stable service",
            "stable service identity",
            "capability groups",
            "capability group",
            "capability boundaries",
            "capability boundary",
            "role mapping",
            "role assignments",
            "role/capability",
            "role-capability",
            "claim mapping",
            "bootstrap configuration",
            "bootstrap process",
            "bootstrap mechanism",
            "operator bootstrap",
            "health checks",
            "health check",
            "diagnostic endpoints",
            "diagnostic output",
            "diagnostics",
            "structured error",
            "structured output",
            "structured logging",
            "structured record",
            "error messages",
            "error message",
            "error output",
            "error without",
            "error with no",
            "error record",
            "explicit error",
            "explicit structured error",
            "without leaking",
            "without exception",
            "without exposing",
            "without redefining",
            "without secret",
            "without real",
            "with no secret",
            "with no real",
            "with no plaintext",
            "with documented",
            "with rotation",
            "with access control",
            "with validated",
            "with explicit",
            "with scoped",
            "with no",
            "with timestamps",
            "with actor",
            "with policy",
            "with hash",
            "with justification",
            "with scope",
            "redaction markers",
            "redaction marker",
            "redaction helper",
            "redaction must",
            "redaction in",
            "redaction rules",
            "redaction and audit",
            "masking rules",
            "masking in",
            "mask or omit",
            "masked in",
            "mask all",
            "masked",
            "sanitized",
            "sanitize",
            "sanitization",
            "sanitized output",
            "sanitized before",
            "replaced by",
            "replaced",
            "replaceable",
            "redefinition",
            "verified",
            "verified by",
            "verified on",
            "verified source",
            "verified startup",
            "verified output",
            "validated configuration",
            "validated on",
            "validated startup",
            "validated source",
            "validated secret",
            "validated environment",
            "validated values",
            "validation rules",
            "validation expects",
            "validation",
            "valid values",
            "valid authentication",
            "valid future",
            "valid provider",
            "valid JSON",
            "invalid secret",
            "invalid or",
            "invalid configuration",
            "invalid values",
            "missing secret",
            "missing secrets",
            "missing required",
            "missing or",
            "missing and",
            "missing if",
            "missing invalid",
            "source code",
            "source name",
            "source names",
            "source through",
            "source expectation",
            "source boundary",
            "source manager",
            "source abstraction",
            "source identifier",
            "source config",
            "source validation",
            "source reference",
            "source from",
            "source only",
            "source must",
            "source may",
            "source and",
            "source or",
            "source with",
            "credential source",
            "credential set",
            "credential values",
            "credential value",
            "credential management",
            "credential configuration",
            "credential with",
            "credential source",
            "credential boundaries",
            "credential boundary",
            "credential sourcing",
            "credential store",
            "credential reference",
            "credential with no",
            "credentials sourced",
            "credentials through",
            "credentials must",
            "credentials may",
            "credentials are",
            "credentials for",
            "credentials with",
            "credentials and",
            "credentials or",
            "credentials in",
            "credentials to",
            "credentials from",
            "credentials at",
            "credentials on",
            "credentials by",
            "credentials without",
            "credentials that",
            "scoped credential",
            "scoped credentials",
            "scoped to",
            "scoped per",
            "scoped access",
            "scoped capabilities",
            "scoped only",
            "backup credentials",
            "backup storage",
            "backup metadata",
            "backup and restore",
            "backup/restore",
            "backup configuration",
            "backup operations",
            "backup schedule",
            "backup runbooks",
            "backup/restore configuration",
            "backup/restore plan",
            "restore procedures",
            "restore storage",
            "restore validation",
            "restore test",
            "restore configuration",
            "restore procedure",
            "point-in-time",
            "disaster runbooks",
            "automated backup",
            "retention policy",
            "retention period",
            "retention expectations",
            "retention and",
            "observability backend",
            "observability stack",
            "observability configuration",
            "observability data",
            "observability sink",
            "observability signals",
            "observability expectation",
            "observability expectations",
            "observability/logging",
            "logging/observability",
            "logging pipeline",
            "logging output",
            "logging rule",
            "logging sink",
            "logging and",
            "logging or",
            "logging must",
            "logging may",
            "logging in",
            "logging configuration",
            "structured logging",
            "metrics",
            "alerting",
            "tracing",
            "health",
            "latency",
            "error rate",
            "prometheus",
            "grafana",
            "slo",
            "distributed tracing",
            "business metrics",
            "ci gate",
            "ci pipeline",
            "ci gating",
            "ci stages",
            "contract freeze",
            "contract review",
            "contract hardening",
            "contract clarity",
            "openapi contract",
            "openapi examples",
            "openapi security",
            "openapi security contract",
            "openapi security schemes",
            "versioning strategy",
            "versioned artifact",
            "versioned and",
            "versioned openapi",
            "deprecated",
            "deprecation policy",
            "breaking-change",
            "kubernetes",
            "docker",
            "container",
            "orchestration",
            "terraform",
            "helm",
            "load balancing",
            "tls termination",
            "network topology",
            "deployment automation",
            "deployment environment",
            "deployment context",
            "deployment specific",
            "deployment readiness",
            "deployment parameters",
            "network exposure",
            "network binding",
            "network hardening",
            "cors",
            "external access",
            "origin allowlisting",
            "host and port",
            "api bind host",
            "api bind port",
            "api server binding",
            "binding and",
            "binding enforcement",
            "tls enabled",
            "tls configuration",
            "sha-256",
            "sha-256 recomparison",
            "ed25519",
            "ed25519 signatures",
            "ed25519 signing",
            "hash computation",
            "hash references",
            "hash-based",
            "tamper detection",
            "tamper evidence",
            "tampering",
            "corruption",
            "completeness scoring",
            "completeness score",
            "integrity constraints",
            "integrity checks",
            "integrity proofs",
            "integrity hashes",
            "blockchain anchoring",
            "blockchain dependency",
            "wallet signing",
            "wallet operations",
            "wallet custody",
            "wallet keys",
            "wallet integration",
            "payment integration",
            "payment keys",
            "payment processing",
            "disbursement",
            "saas",
            "multi-tenant",
            "tenant isolation",
            "tenant management",
            "subscription billing",
            "onboarding",
            "per-tenant",
            "sdk",
            "client libraries",
            "client examples",
            "client layer",
            "ui layer",
            "dashboard clients",
            "dashboard product",
            "dashboard/ui",
            "frontend",
            "react",
            "vue",
            "mobile",
            "accessibility",
            "legal review",
            "regulatory review",
            "compliance certification",
            "compliance/legal",
            "data-classification",
            "evidence retention",
            "retention policy",
            "retention periods",
            "immutable storage",
            "deletion constraints",
            "privacy",
            "legal boundary",
            "security review",
            "external partners",
            "partner agreement",
            "partner-agreed",
            "partner system",
            "partner facing",
            "partner integration",
            "partner environment",
            "partner-specific",
            "partner-agreed config",
            "partner-agreed authentication",
            "partner-agreed secret",
            "integrators",
            "integration patterns",
            "integration guide",
            "integration ready",
            "integration checklist",
            "integration contract",
            "integration boundary",
            "integration tests",
            "integration test",
            "integration path",
            "integration surface",
            "integration access",
            "integration queries",
            "integration with",
            "external integrations",
            "external integration",
            "external systems",
            "external services",
            "external clients",
            "external access",
            "external identity",
            "external provider",
            "external secret",
            "external workflow",
            "external evidence",
            "external feeds",
            "third-party",
            "third party",
            "hsm",
            "hsm-backed",
            "hsm integration",
            "kms",
            "kms integration",
            "key management service",
            "vault integration",
            "hashicorp vault",
            "aws secrets manager",
            "azure key vault",
            "google secret manager",
            "cloud secret",
            "cloud secret manager",
            "environment variable",
            "environment variables",
            "environment boundary",
            "environment model",
            "env var",
            "feature flag",
            "extension toggle",
            "extension surface",
            "adapter boundary",
            "adapter output",
            "adapter target",
            "adapter interface",
            "adapter framework",
            "adapter behavior",
            "adapter rules",
            "adapter integration",
            "adapter must",
            "adapter should",
            "pluggable",
            "plugin",
            "plugin runtime",
            "mock",
            "fixture",
            "fixtures",
            "smoke",
            "smoke manifest",
            "smoke script",
            "dry-run",
            "dry run",
            "placeholder",
            "placeholders",
            "synthetic",
            "demo",
            "demonstration",
            "walkthrough",
            "illustrative",
            "developer convenience",
            "dev",
            "ci",
            "test suite",
            "test output",
            "test fixture",
            "test fixtures",
            "test identity",
            "test only",
            "test-only",
            "automated tests",
            "automated verification",
            "automated backup",
            "manual deployment",
            "manual secret",
            "shared access",
            "shared secret",
            "shared token",
            "shared artifacts",
            "public contracts",
            "public ledgers",
            "public grant",
            "public discovery",
            "matchmaking",
            "on-chain",
            "off-chain",
            "off-chain storage",
            "off-chain in",
            "on-chain data",
            "on-chain plaintext",
            "on-chain value",
            "git history",
            "git",
            "screenshots",
            "artifacts",
            "artifact",
            "related artifacts",
            "machine-readable",
            "human-readable",
            "static json",
            "json fixtures",
            "json examples",
            "json files",
            "quickstart",
            "quickstart examples",
            "quickstart docs",
            "handoff",
            "handoff plan",
            "release candidate",
            "release decision",
            "pilot-ready",
            "pilot ready",
            "pilot partner",
            "pilot-specific",
            "pilot discussion",
            "pilot validation",
            "pilot feedback",
            "pilot artifact",
            "pilot handoff",
            "pilot release",
            "technical pilot",
            "first pilot",
            "pilot",
            "production-ready",
            "production ready",
            "not production-ready",
            "integration-ready",
            "integration ready",
            "pilot-ready for technical review",
            "product foundation",
            "product foundation planning",
            "product foundation security",
            "non-production default",
            "non-production labeling",
            "non-production constraint",
            "non-production warning",
            "non-production walkthrough",
            "non-production mode",
            "non-production modes",
            "no real secret",
            "no real secrets",
            "no real credentials",
            "no real credential values",
            "no real values",
            "no real value",
            "no production observability",
            "no production secret manager",
            "no backup/restore",
            "no backup guarantee",
            "no network exposure",
            "no external dependencies",
            "no external secret manager",
            "container",
            "container layout",
            "container orchestration",
            "host",
            "hosted",
            "hosting platform",
            "bare-metal",
            "cloud",
            "cloud deployment",
            "orchestration",
            "deployment package",
            "deployment packages",
            "deployment artifact",
            "deployment artifacts",
            "deployment-specific",
            "deployment specific",
            "deployment configuration",
            "deployment config",
            "deployment mode",
            "deployment modes",
            "deployment mode mapping",
            "deployment mode to deployment mode mapping",
            "deployment expectation",
            "deployment expectations",
            "deployment style",
            "deployment target",
            "deployment targets",
            "deployment boundary",
            "deployment boundaries",
            "deployment behavior",
            "deployment context",
            "deployment environment",
            "deployment environments",
            "network topology",
            "network exposure",
            "network exposure rules",
            "network binding",
            "network hardening",
            "docker",
            "docker-compose",
            "docker compose",
            "dockerfile",
            "docker secrets",
            "kubernetes",
            "kubernetes manifests",
            "k8s",
            "helm",
            "terraform",
            "reverse proxy",
            "reverse_proxy",
            "tls automation",
            "tls termination",
            "tls enabled",
            "tls configuration",
            "load balancing",
            "ci packaging",
            "ci packaging validation",
            "ci pipeline",
            "ci gating",
            "ci stages",
            "ci gate",
            "ci",
            "production ci/cd",
            "production cicd",
            "monitoring stack",
            "monitoring",
            "backup system",
            "backup system implementation",
            "production database automation",
            "hosted saas platform",
            "hosted saas",
            "multi-tenant deployment",
            "multi tenant deployment",
            "secret manager integration",
            "secret manager integration implementation",
            "observability implementation",
            "observability stack implementation",
            "package checklist",
            "packaging checklist",
            "reference package",
            "reference package expectation",
            "runnable application package",
            "operator runbook",
            "upgrade migration notes",
            "extension adaptor",
            "extension adaptor configuration",
            "extension adapter",
            "extension adapter configuration",
        ]
        result = text.lower()
        for term in sorted(safe_terms, key=len, reverse=True):
            result = result.replace(term.lower(), "")
        return result

    def test_no_obvious_secrets_in_matrix(self):
        text_lower = self._sanitize_known_safe_terms(self.matrix_text)
        for pattern in self.SECRET_PATTERNS:
            self.assertNotIn(
                pattern,
                text_lower,
                f"Matrix may contain secret-like pattern: {pattern}",
            )

    def test_no_obvious_secrets_in_catalog(self):
        text_lower = self._sanitize_known_safe_terms(self.catalog_text)
        for pattern in self.SECRET_PATTERNS:
            self.assertNotIn(
                pattern,
                text_lower,
                f"Catalog may contain secret-like pattern: {pattern}",
            )

    # ── 14. Forbidden implementation files were not introduced ────────
    def test_no_forbidden_implementation_files_introduced(self):
        for forbidden in self.FORBIDDEN_PATH_PATTERNS:
            if forbidden.exists():
                self.fail(
                    f"Forbidden implementation file must not exist: {forbidden}"
                )

    # ── Extra coherence checks ────────────────────────────────────────
    def test_matrix_has_id_and_version(self):
        self.assertEqual(
            self.matrix_json.get("matrixId"),
            "gl069-deployment-runtime-mode-matrix",
        )
        self.assertEqual(self.matrix_json.get("matrixVersion"), "1.0")

    def test_matrix_status_is_product_foundation_planning(self):
        self.assertEqual(self.matrix_json.get("status"), "product-foundation-planning")

    def test_catalog_has_id_and_version(self):
        self.assertEqual(
            self.catalog_json.get("catalogId"),
            "gl069-deployment-package-catalog",
        )
        self.assertEqual(self.catalog_json.get("catalogVersion"), "1.0")

    def test_catalog_status_is_product_foundation_planning(self):
        self.assertEqual(self.catalog_json.get("status"), "product-foundation-planning")

    def test_matrix_includes_deployment_claim_rules(self):
        rules = self.matrix_json.get("deploymentClaimRules", [])
        self.assertTrue(len(rules) > 0, "Matrix must include deploymentClaimRules")

    def test_catalog_includes_deployment_boundaries(self):
        boundaries = self.catalog_json.get("deploymentBoundaries", [])
        self.assertTrue(len(boundaries) > 0, "Catalog must include deploymentBoundaries")
        text = " ".join([b.get("boundary", "") for b in boundaries]).lower()
        self.assertIn("product core should not depend on one hosting platform", text)

    def test_catalog_includes_reference_package_expectations(self):
        expectations = self.catalog_json.get("referencePackageExpectations", [])
        self.assertTrue(len(expectations) > 0, "Catalog must include referencePackageExpectations")
        text = " ".join(expectations).lower()
        self.assertIn("operator runbook", text)
        self.assertIn("openapi", text)

    def test_catalog_includes_production_required_configuration(self):
        required = self.catalog_json.get("productionRequiredConfiguration", [])
        self.assertTrue(len(required) > 0, "Catalog must include productionRequiredConfiguration")

    def test_catalog_includes_implementation_non_goals(self):
        non_goals = self.catalog_json.get("implementationNonGoals", [])
        self.assertTrue(len(non_goals) > 0, "Catalog must include implementationNonGoals")
        text = " ".join(non_goals).lower()
        self.assertIn("dockerfile", text)
        self.assertIn("kubernetes", text)

    def test_doc_includes_product_deployment_principle(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("product deployment principle", content)
        self.assertIn("separate product package", content)

    def test_doc_includes_runtime_mode_to_deployment_mode_mapping(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("runtime mode to deployment mode mapping", content)
        self.assertIn("local-dev", content)
        self.assertIn("production", content)

    def test_doc_includes_deployment_package_components(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("deployment package components", content)
        self.assertIn("application package", content)
        self.assertIn("operator runbook", content)

    def test_doc_includes_safe_local_test_demo_defaults(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("safe local / test / demo package defaults", content)
        self.assertIn("sqlite", content)
        self.assertIn("local-only api binding", content)

    def test_doc_includes_production_required_deployment_behavior(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("production-required deployment behavior", content)
        self.assertIn("fail-closed", content)

    def test_doc_includes_deployment_boundaries(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("deployment boundaries", content)
        self.assertIn("product core should not depend on one hosting platform", content)

    def test_doc_includes_reference_package_expectation(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("reference package expectation", content)
        self.assertIn("openapi contract artifact", content)

    def test_doc_includes_future_implementation_expectations(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("future implementation expectations", content)
        self.assertIn("configuration schema / loader", content)
        self.assertIn("health / readiness check baseline", content)

    def test_doc_includes_what_not_to_implement_yet(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("what not to implement yet", content)
        self.assertIn("dockerfile", content)
        self.assertIn("kubernetes", content)

    def test_doc_includes_decision_boundary(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("decision boundary", content)

    def test_doc_references_gl068(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("gl-068", content)

    def test_doc_references_gl067(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("gl-067", content)

    def test_doc_references_gl066(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("gl-066", content)

    def test_doc_references_gl065(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("gl-065", content)

    def test_doc_references_gl063(self):
        content = self.doc_path.read_text(encoding="utf-8").lower()
        self.assertIn("gl-063", content)

    def test_matrix_references_related_artifacts(self):
        artifacts = self.matrix_json.get("relatedArtifacts", [])
        self.assertTrue(len(artifacts) > 0, "Matrix must include relatedArtifacts")

    def test_catalog_references_related_artifacts(self):
        artifacts = self.catalog_json.get("relatedArtifacts", [])
        self.assertTrue(len(artifacts) > 0, "Catalog must include relatedArtifacts")

    def test_catalog_package_components_mark_secret_bearing(self):
        components = self.catalog_json.get("packageComponents", [])
        secret_bearing_count = 0
        for component in components:
            if component.get("secretBearing") is True:
                secret_bearing_count += 1
        self.assertGreater(
            secret_bearing_count,
            0,
            "At least one package component must be marked secretBearing",
        )

    def test_catalog_package_components_distinguish_local_demo(self):
        components = self.catalog_json.get("packageComponents", [])
        local_demo_count = 0
        production_count = 0
        for component in components:
            if component.get("requiredForLocalDemo") is True:
                local_demo_count += 1
            if component.get("requiredForProduction") is True:
                production_count += 1
        self.assertGreater(local_demo_count, 0, "At least one component must be requiredForLocalDemo")
        self.assertGreater(production_count, 0, "At least one component must be requiredForProduction")


if __name__ == "__main__":
    unittest.main(verbosity=2)
