"""initial schema

Revision ID: 1073cc9e6514
Revises: 
Create Date: 2026-06-12 17:37:17.774461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1073cc9e6514'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('matched_grant_id', sa.Text(), nullable=True),
    sa.Column('challenge_id', sa.Text(), nullable=True),
    sa.Column('challenge_present', sa.Integer(), nullable=True),
    sa.Column('challenge_result', sa.Text(), nullable=True),
    sa.Column('grant_signature_result', sa.Text(), nullable=True),
    sa.Column('row_hash', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_events_tenant_id', 'audit_events', ['tenant_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('used_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_challenges_tenant_id', 'challenges', ['tenant_id'], unique=False)
    op.create_table('evidence_archives',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('evidence_hash', sa.Text(), nullable=False),
    sa.Column('canonical_version', sa.Text(), nullable=False),
    sa.Column('hash_algorithm', sa.Text(), nullable=False),
    sa.Column('bundle_json', sa.Text(), nullable=False),
    sa.Column('execution_id', sa.Text(), nullable=False),
    sa.Column('grant_id', sa.Text(), nullable=True),
    sa.Column('grant_request_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('stored_by', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.Text(), nullable=True),
    sa.Column('last_verification_status', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_index('idx_evidence_archives_created_at', 'evidence_archives', ['created_at'], unique=False)
    op.create_index('idx_evidence_archives_execution_id', 'evidence_archives', ['execution_id'], unique=False)
    op.create_index('idx_evidence_archives_grant_id', 'evidence_archives', ['grant_id'], unique=False)
    op.create_index('idx_evidence_archives_tenant_id', 'evidence_archives', ['tenant_id'], unique=False)
    op.create_table('evidence_hashes',
    sa.Column('evidence_hash', sa.Text(), nullable=False),
    sa.Column('archive_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('evidence_hash')
    )
    op.create_index('idx_evidence_hashes_archive_id', 'evidence_hashes', ['archive_id'], unique=False)
    op.create_table('grant_executions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('grant_id', sa.Text(), nullable=True),
    sa.Column('grant_request_id', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('challenge_id', sa.Text(), nullable=True),
    sa.Column('challenge_result', sa.Text(), nullable=True),
    sa.Column('policy_result', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.Text(), nullable=False),
    sa.Column('audit_event_id', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grant_executions_executed_at', 'grant_executions', ['executed_at'], unique=False)
    op.create_index('idx_grant_executions_grant_id', 'grant_executions', ['grant_id'], unique=False)
    op.create_index('idx_grant_executions_grant_request_id', 'grant_executions', ['grant_request_id'], unique=False)
    op.create_index('idx_grant_executions_operator_id', 'grant_executions', ['operator_id'], unique=False)
    op.create_index('idx_grant_executions_tenant_id', 'grant_executions', ['tenant_id'], unique=False)
    op.create_table('grant_requests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Text(), nullable=False),
    sa.Column('valid_until', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.Text(), nullable=True),
    sa.Column('denied_by', sa.Text(), nullable=True),
    sa.Column('denied_at', sa.Text(), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('revoked_by', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.Text(), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('grant_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grant_requests_tenant_id', 'grant_requests', ['tenant_id'], unique=False)
    op.create_table('grants',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Text(), nullable=False),
    sa.Column('valid_until', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('revoked', sa.Integer(), nullable=False),
    sa.Column('revoked_by', sa.Text(), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('signing_key_id', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.Text(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grants_tenant_id', 'grants', ['tenant_id'], unique=False)
    op.create_index('idx_grants_tenant_subject', 'grants', ['tenant_id', 'subject_id'], unique=False)
    op.create_table('operators',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('token_lookup_hash', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Text(), nullable=True),
    sa.Column('rotated_at', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operators_tenant_id', 'operators', ['tenant_id'], unique=False)
    op.create_index('idx_operators_token_lookup_hash', 'operators', ['token_lookup_hash'], unique=False)
    op.create_table('provenance_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('execution_id', sa.Text(), nullable=True),
    sa.Column('grant_id', sa.Text(), nullable=True),
    sa.Column('evidence_hash', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provenance_events_actor_type', 'provenance_events', ['actor_type'], unique=False)
    op.create_index('idx_provenance_events_execution_id', 'provenance_events', ['execution_id'], unique=False)
    op.create_index('idx_provenance_events_grant_id', 'provenance_events', ['grant_id'], unique=False)
    op.create_index('idx_provenance_events_occurred_at', 'provenance_events', ['occurred_at'], unique=False)
    op.create_index('idx_provenance_events_resource_type_resource_id', 'provenance_events', ['resource_type', 'resource_id'], unique=False)
    op.create_table('workspace_invites',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('invited_by', sa.Text(), nullable=False),
    sa.Column('email_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workspace_invites_email_hash', 'workspace_invites', ['email_hash'], unique=False)
    op.create_index('idx_workspace_invites_workspace_id', 'workspace_invites', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('operator_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('invited_by', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'operator_id', name='idx_workspace_members_workspace_operator')
    )
    op.create_index('idx_workspace_members_operator_id', 'workspace_members', ['operator_id'], unique=False)
    op.create_index('idx_workspace_members_workspace_id', 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workspaces_tenant_id', 'workspaces', ['tenant_id'], unique=False)
    op.create_index('idx_workspaces_tenant_slug', 'workspaces', ['tenant_id', 'slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workspaces_tenant_slug', table_name='workspaces')
    op.drop_index('idx_workspaces_tenant_id', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('idx_workspace_members_workspace_id', table_name='workspace_members')
    op.drop_index('idx_workspace_members_operator_id', table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('idx_workspace_invites_workspace_id', table_name='workspace_invites')
    op.drop_index('idx_workspace_invites_email_hash', table_name='workspace_invites')
    op.drop_table('workspace_invites')
    op.drop_index('idx_provenance_events_resource_type_resource_id', table_name='provenance_events')
    op.drop_index('idx_provenance_events_occurred_at', table_name='provenance_events')
    op.drop_index('idx_provenance_events_grant_id', table_name='provenance_events')
    op.drop_index('idx_provenance_events_execution_id', table_name='provenance_events')
    op.drop_index('idx_provenance_events_actor_type', table_name='provenance_events')
    op.drop_table('provenance_events')
    op.drop_index('idx_operators_token_lookup_hash', table_name='operators')
    op.drop_index('idx_operators_tenant_id', table_name='operators')
    op.drop_table('operators')
    op.drop_index('idx_grants_tenant_subject', table_name='grants')
    op.drop_index('idx_grants_tenant_id', table_name='grants')
    op.drop_table('grants')
    op.drop_index('idx_grant_requests_tenant_id', table_name='grant_requests')
    op.drop_table('grant_requests')
    op.drop_index('idx_grant_executions_tenant_id', table_name='grant_executions')
    op.drop_index('idx_grant_executions_operator_id', table_name='grant_executions')
    op.drop_index('idx_grant_executions_grant_request_id', table_name='grant_executions')
    op.drop_index('idx_grant_executions_grant_id', table_name='grant_executions')
    op.drop_index('idx_grant_executions_executed_at', table_name='grant_executions')
    op.drop_table('grant_executions')
    op.drop_index('idx_evidence_hashes_archive_id', table_name='evidence_hashes')
    op.drop_table('evidence_hashes')
    op.drop_index('idx_evidence_archives_tenant_id', table_name='evidence_archives')
    op.drop_index('idx_evidence_archives_grant_id', table_name='evidence_archives')
    op.drop_index('idx_evidence_archives_execution_id', table_name='evidence_archives')
    op.drop_index('idx_evidence_archives_created_at', table_name='evidence_archives')
    op.drop_table('evidence_archives')
    op.drop_index('idx_challenges_tenant_id', table_name='challenges')
    op.drop_table('challenges')
    op.drop_index('idx_audit_events_tenant_id', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
